require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FindsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Find. As you add validations to Find, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FindsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all finds as @finds" do
      find = Find.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:finds)).to eq([find])
    end
  end

  describe "GET show" do
    it "assigns the requested find as @find" do
      find = Find.create! valid_attributes
      get :show, {:id => find.to_param}, valid_session
      expect(assigns(:find)).to eq(find)
    end
  end

  describe "GET new" do
    it "assigns a new find as @find" do
      get :new, {}, valid_session
      expect(assigns(:find)).to be_a_new(Find)
    end
  end

  describe "GET edit" do
    it "assigns the requested find as @find" do
      find = Find.create! valid_attributes
      get :edit, {:id => find.to_param}, valid_session
      expect(assigns(:find)).to eq(find)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Find" do
        expect {
          post :create, {:find => valid_attributes}, valid_session
        }.to change(Find, :count).by(1)
      end

      it "assigns a newly created find as @find" do
        post :create, {:find => valid_attributes}, valid_session
        expect(assigns(:find)).to be_a(Find)
        expect(assigns(:find)).to be_persisted
      end

      it "redirects to the created find" do
        post :create, {:find => valid_attributes}, valid_session
        expect(response).to redirect_to(Find.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved find as @find" do
        post :create, {:find => invalid_attributes}, valid_session
        expect(assigns(:find)).to be_a_new(Find)
      end

      it "re-renders the 'new' template" do
        post :create, {:find => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested find" do
        find = Find.create! valid_attributes
        put :update, {:id => find.to_param, :find => new_attributes}, valid_session
        find.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested find as @find" do
        find = Find.create! valid_attributes
        put :update, {:id => find.to_param, :find => valid_attributes}, valid_session
        expect(assigns(:find)).to eq(find)
      end

      it "redirects to the find" do
        find = Find.create! valid_attributes
        put :update, {:id => find.to_param, :find => valid_attributes}, valid_session
        expect(response).to redirect_to(find)
      end
    end

    describe "with invalid params" do
      it "assigns the find as @find" do
        find = Find.create! valid_attributes
        put :update, {:id => find.to_param, :find => invalid_attributes}, valid_session
        expect(assigns(:find)).to eq(find)
      end

      it "re-renders the 'edit' template" do
        find = Find.create! valid_attributes
        put :update, {:id => find.to_param, :find => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested find" do
      find = Find.create! valid_attributes
      expect {
        delete :destroy, {:id => find.to_param}, valid_session
      }.to change(Find, :count).by(-1)
    end

    it "redirects to the finds list" do
      find = Find.create! valid_attributes
      delete :destroy, {:id => find.to_param}, valid_session
      expect(response).to redirect_to(finds_url)
    end
  end

end
